image:
  file: config/gitpod/Dockerfile

ports:
  - port: 25565
    onOpen: notify

vscode:
  extensions:
    - redhat.java
    - richardwillis.vscode-gradle
    - vscjava.vscode-java-debug


tasks:
  - name: Setup pre-commit hool
    init: pre-commit install --config config/pre-commit/config.yml --allow-missing-config
